const Constants = {
  REGISTRATIONS_ERROR: 'REGISTRATIONS_ERROR',
  SESSIONS_ERROR: 'SESSIONS_ERROR',
  CURRENT_USER: 'CURRENT_USER',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
};

export default Constants;
