const Constants = {
  REGISTRATIONS_ERROR: 'REGISTRATIONS_ERROR',
  SESSIONS_ERROR: 'SESSIONS_ERROR',
  CURRENT_USER: 'CURRENT_USER',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',

  EVENTS_FETCHING: 'EVENTS_FETCHING',
  EVENTS_RECEIVED: 'EVENTS_RECEIVED',
  EVENTS_NEW_EVENT_CREATED: 'EVENTS_NEW_EVENT_CREATED',
  EVENTS_CREATE_ERROR: 'EVENTS_CREATE_ERROR',
  EVENTS_SHOW_FORM: 'EVENTS_SHOW_FORM',
  EVENTS_RESET: 'EVENTS_RESET',
};

export default Constants;
